name: CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install uv
      run: pip install uv

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Initialize uv environment
      run: uv run pip install .

    - name: Create test data directory
      run: |
        mkdir -p mantis/test_data
        touch mantis/test_data/mock_audio.mp3

    # Tests have been intentionally removed from the repository
    # Keeping linting and formatting checks

    - name: Lint with flake8
      run: |
        uv run pip install flake8
        uv run flake8 mantis --count --select=E9,F63,F7,F82 --show-source --statistics
        uv run flake8 mantis --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check formatting with black
      run: |
        uv run pip install black
        uv run black --check mantis

    # Coverage steps removed as they depend on tests 

  publish:
    needs: build
    runs-on: ubuntu-latest
    # Only publish on push to main or on tag push
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload dist/*
